apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw-factory
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jagz70/k8s-openclaw-lab.git
    targetRevision: main
    path: instances/openclaw-factory
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw-factory
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
