kubeProxyReplacement: true
k8sServiceHost: openclaw-lab-control-plane
k8sServicePort: 6443

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

operator:
  replicas: 2

ipam:
  mode: kubernetes
